enum MessageTypeEnum {
  text,
  image,
  video,
  audio,
  file,
  //location,
  //contact,
  sticker,
  //gif,
  voiceCall,
  videoCall,
  missedCall,
  // incomingCall,
  // outgoingCall,
  // groupVoiceCall,
  // groupVideoCall,
  // groupMissedCall,
  // groupIncomingCall,
  // groupOutgoingCall,
  // groupCallEnd,
  // groupVoiceCallEnd,
  // groupVideoCallEnd,
  // groupMissedCallEnd,
  // groupIncomingCallEnd,
  // groupOutgoingCallEnd,
  // groupCallStart,
  // groupVoiceCallStart,
  // groupVideoCallStart,
  // groupMissedCallStart,
  // groupIncomingCallStart,
  // groupOutgoingCallStart,
}
